"use strict";
/// <reference path="./custom.d.ts" />
// tslint:disable
/**
 * Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
exports.__esModule = true;
var portableFetch = fetch;
//const BASE_PATH = "http://220.165.143.73:666".replace(/\/+$/, "");
var BASE_PATH = location.host.indexOf('localhost') >= 0 || location.host.indexOf('127.0.0.1') >= 0
    ? (location.protocol + "//" + location.host + "/api").replace(/\/+$/, '')
    : (location.protocol + "//" + location.host).replace(/\/+$/, '');
/**
 *
 * @export
 
