// <auto-generated />
namespace QC.MF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class zhuhang2019916 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(zhuhang2019916));
        
        string IMigrationMetadata.Id
        {
            get { return "201909161411505_zhuhang2019916"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
