// <auto-generated />
namespace QC.MF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class zhuhang20199161941 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(zhuhang20199161941));
        
        string IMigrationMetadata.Id
        {
            get { return "201909161141465_zhuhang20199161941"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
