// <auto-generated />
namespace QC.MF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class yuanhui20191010 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(yuanhui20191010));
        
        string IMigrationMetadata.Id
        {
            get { return "201910101251180_yuanhui20191010"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
