// <auto-generated />
namespace QC.MF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class lubinrui201909241610 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lubinrui201909241610));
        
        string IMigrationMetadata.Id
        {
            get { return "201909240810561_lubinrui201909241610"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
